#!/bin/bash

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $current_branch == 'main' ]; then
	echo "Impossible de push en main branch !"
	exit 1
fi

if [ $current_branch != 'master' ]; then
 	exit 0
fi

echo -e "N'oublie pas de déployer le rendu sur la vogsphere !\nAvec : bash hooks/deploy\n\nPushing...\n"

exit 0
